### ISSUE TITLE
CircleCI build broken by pip alert

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#1020] opened 2020-09-11 17:20 UTC
CircleCI builds [e.g., job 2973](https://app.circleci.com/pipelines/github/GovReady/govready-q/835/workflows/9a5cf4b5-120f-4196-8151-6668f88ea576/jobs/2973) started to fail, apparently with the following error:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
```

To resolve this ticket, check and resolve what to do about `pip` changes coming in October 2020.

**Comment by gregelin** [comment] 2020-09-20 12:56
Closer reading indicated that error was caused by checksum of Google fonts being changed. Fixed in #cb6f4729.

**Closed** 2020-09-20 12:56 UTC
